// Typed model catalog — the human-authored source of truth for seeded models.
// Flags default to false; list only the ones that are true.
// Seeded into the database at startup by seedModelsFromCatalog (./modelSeed.ts) — there
// is no generated SQL file. Edit and commit; the change seeds on the next boot.
// Run `bun run check-models` to validate the per-provider invariants offline.

import type { EmbeddingInput, ImageInput, LlmInput, ModelSection, VideoInput } from "./types";

export const llmSections: ModelSection<LlmInput>[] = [
  {
    comment: "Google Models (all Gemini models support vision, videos, YouTube, and structured output)",
    rows: [
      {
        provider: "google",
        codename: "gemini-2.0-flash",
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: null,
        ja: null,
      },
      {
        provider: "google",
        codename: "gemini-2.5-flash-lite",
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Lightweight version optimized for speed and efficiency",
        ja: "速度と効率を最適化した軽量版モデル",
      },
      {
        provider: "google",
        codename: "gemini-2.5-flash-preview-05-20",
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: null,
        ja: null,
      },
      {
        provider: "google",
        codename: "gemini-2.5-flash-preview-09-2025",
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Experimental model for general-purpose applications (deprecated, use gemini-2.5-flash)",
        ja: "実験的な汎用アプリケーション向けモデル（非推奨、gemini-2.5-flashを使用）",
      },
      {
        provider: "google",
        codename: "gemini-2.5-flash",
        isDefault: true,
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Balanced model for general-purpose applications",
        ja: "汎用アプリケーション向けのバランス型モデル",
      },
      {
        provider: "google",
        codename: "gemini-2.5-pro",
        isSmartest: true,
        isReasoning: true,
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Most capable model for complex reasoning and analysis",
        ja: "複雑な推論と分析に最も優れたモデル",
      },
      {
        provider: "google",
        codename: "gemini-3-flash",
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Latest model with enhanced performance and capabilities",
        ja: "強化されたパフォーマンスと機能を備えた最新のモデル",
      },
      {
        provider: "google",
        codename: "gemini-3-flash-preview",
        isFree: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest preview model with enhanced performance and capabilities (deprecated, use gemini-3-flash)",
        ja: "強化されたパフォーマンスと機能を備えた最新のプレビューモデル（非推奨、gemini-3-flashを使用）",
      },
      {
        provider: "google",
        codename: "gemini-3.1-flash-lite-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest Gemini 3.1 Flash Lite preview model with full multimodal and tool capabilities (deprecated, use gemini-3.5-flash)",
        ja: "ツール利用を含むフルマルチモーダル機能に対応した最新のGemini 3.1 Flash Liteプレビューモデル（非推奨、gemini-3.5-flashを使用）",
      },
      {
        provider: "google",
        codename: "gemini-3.1-flash-lite",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Gemini 3.1 Flash Lite stable model with full multimodal and tool capabilities",
        ja: "ツール利用を含むフルマルチモーダル機能に対応したGemini 3.1 Flash Lite安定版モデル",
      },
      {
        provider: "google",
        codename: "gemini-3.5-flash",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Fast and efficient Gemini 3.5 Flash model for general-purpose applications",
        ja: "汎用アプリケーション向けの高速で効率的なGemini 3.5 Flashモデル",
      },
      {
        provider: "google",
        codename: "gemini-3.5-pro",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Advanced Gemini 3.5 Pro model for complex reasoning and analysis",
        ja: "複雑な推論と分析向けの高度なGemini 3.5 Proモデル",
      },
      {
        provider: "google",
        codename: "gemini-3-pro-preview",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Preview model focused on advanced reasoning and analysis (deprecated, use gemini-3.1-pro-preview)",
        ja: "高度な推論と分析に特化したプレビューモデル（非推奨、gemini-3.1-pro-preview を使用）",
      },
      {
        provider: "google",
        codename: "gemini-3.1-pro",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Latest Gemini 3.1 Pro model focused on advanced reasoning and analysis",
        ja: "高度な推論と分析に特化した最新のGemini 3.1 Proモデル",
      },
      {
        provider: "google",
        codename: "gemini-3.1-pro-preview",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest Gemini 3.1 Pro preview model focused on advanced reasoning and analysis (deprecated, use gemini-3.1-pro)",
        ja: "高度な推論と分析に特化した最新のGemini 3.1 Proプレビューモデル（非推奨、gemini-3.1-proを使用）",
      },
      {
        provider: "google",
        codename: "gemma-4-31b-it",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        supportsStructoutput: true,
        desc: "Google Gemma 4.31B IT model with tool use, image understanding, video understanding, and structured output support",
        ja: "ツール利用・画像理解・動画理解・構造化出力に対応するGoogleのGemma 4.31B ITモデル",
      },
      {
        provider: "google",
        codename: "gemma-4-26b-a4b-it",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        supportsStructoutput: true,
        desc: "Google Gemma 4 26B A4B IT MoE model with tool use, image understanding, video understanding, and structured output support",
        ja: "ツール利用・画像理解・動画理解・構造化出力に対応するGoogleのGemma 4 26B A4B IT MoEモデル",
      },
      {
        provider: "google",
        codename: "gemma-3-27b-it",
        isFree: true,
        seesImages: true,
        isDeprecated: true,
        desc: "Instruction-tuned Gemma model with image understanding",
        ja: "画像理解に対応した指示調整済みGemmaモデル",
      },
    ],
  },
  {
    comment: "Vertex AI Models (full feature parity with Google AI Studio via ADC)",
    rows: [
      {
        provider: "vertex",
        codename: "gemini-2.5-flash-lite",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Lightweight version optimized for speed and efficiency via Vertex AI",
        ja: "Vertex AI経由の速度と効率を最適化した軽量版モデル",
      },
      {
        provider: "vertex",
        codename: "gemini-2.5-flash",
        isDefault: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Balanced model for general-purpose applications via Vertex AI",
        ja: "Vertex AI経由の汎用アプリケーション向けバランス型モデル",
      },
      {
        provider: "vertex",
        codename: "gemini-2.5-pro",
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Most capable model for complex reasoning and analysis via Vertex AI",
        ja: "Vertex AI経由の複雑な推論と分析に最も優れたモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3-flash",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Latest model with enhanced performance and capabilities via Vertex AI",
        ja: "Vertex AI経由の強化されたパフォーマンスと機能を備えた最新のモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3-flash-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest preview model with enhanced performance and capabilities via Vertex AI (deprecated, use gemini-3-flash)",
        ja: "Vertex AI経由の強化されたパフォーマンスと機能を備えた最新のプレビューモデル（非推奨、gemini-3-flashを使用）",
      },
      {
        provider: "vertex",
        codename: "gemini-3.1-flash-lite-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest Gemini 3.1 Flash Lite preview model with full multimodal and tool capabilities via Vertex AI (deprecated, use gemini-3.5-flash)",
        ja: "Vertex AI経由のツール利用を含むフルマルチモーダル機能に対応した最新のGemini 3.1 Flash Liteプレビューモデル（非推奨、gemini-3.5-flashを使用）",
      },
      {
        provider: "vertex",
        codename: "gemini-3.1-flash-lite",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Gemini 3.1 Flash Lite stable model with full multimodal and tool capabilities via Vertex AI",
        ja: "Vertex AI経由のツール利用を含むフルマルチモーダル機能に対応したGemini 3.1 Flash Lite安定版モデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3.5-flash",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Fast and efficient Gemini 3.5 Flash model for general-purpose applications via Vertex AI",
        ja: "Vertex AI経由の汎用アプリケーション向けの高速で効率的なGemini 3.5 Flashモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3.5-pro",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Advanced Gemini 3.5 Pro model for complex reasoning and analysis via Vertex AI",
        ja: "Vertex AI経由の複雑な推論と分析向けの高度なGemini 3.5 Proモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3.1-pro",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Latest Gemini 3.1 Pro model focused on advanced reasoning and analysis via Vertex AI",
        ja: "Vertex AI経由の高度な推論と分析に特化した最新のGemini 3.1 Proモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3.1-pro-preview",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest Gemini 3.1 Pro preview model focused on advanced reasoning and analysis via Vertex AI (deprecated, use gemini-3.1-pro)",
        ja: "Vertex AI経由の高度な推論と分析に特化した最新のGemini 3.1 Proプレビューモデル（非推奨、gemini-3.1-proを使用）",
      },
      {
        provider: "vertex",
        codename: "gemma-4-31b-it",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Vision-capable Vertex-hosted Gemma 4.31B IT model with tool use and structured output (video disabled)",
        ja: "動画非対応ながらツール利用と構造化出力をサポートするVertex AI向けGemma 4.31B ITモデル",
      },
      {
        provider: "vertex",
        codename: "gemma-3-27b-it",
        seesImages: true,
        isDeprecated: true,
        desc: "Instruction-tuned Gemma model with image understanding via Vertex AI",
        ja: "Vertex AI経由の画像理解に対応した指示調整済みGemmaモデル",
      },
    ],
  },
  {
    comment: "Vertex AI Express Models (Gemini-only Express Mode subset; no video, YouTube, or embeddings)",
    rows: [
      {
        provider: "vertexexpress",
        codename: "gemini-2.0-flash-001",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Gemini 2.0 Flash model available through Vertex AI Express",
        ja: "Vertex AI Expressで利用できるGemini 2.0 Flashモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-2.0-flash-lite-001",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Gemini 2.0 Flash Lite model available through Vertex AI Express",
        ja: "Vertex AI Expressで利用できるGemini 2.0 Flash Liteモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-2.5-flash-lite-09-2025",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Gemini 2.5 Flash Lite model available through Vertex AI Express",
        ja: "Vertex AI Expressで利用できるGemini 2.5 Flash Liteモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-2.5-flash-lite-preview-09-2025",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Preview Gemini 2.5 Flash Lite model available through Vertex AI Express (deprecated, use gemini-2.5-flash-lite-09-2025)",
        ja: "Vertex AI Expressで利用できるGemini 2.5 Flash Liteプレビューモデル（非推奨、gemini-2.5-flash-lite-09-2025を使用）",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-2.5-flash-lite",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Lightweight Gemini 2.5 Flash Lite model via Vertex AI Express",
        ja: "Vertex AI Express経由の軽量Gemini 2.5 Flash Liteモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-2.5-flash",
        isDefault: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Balanced Gemini 2.5 Flash model via Vertex AI Express",
        ja: "Vertex AI Express経由のバランス型Gemini 2.5 Flashモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-2.5-pro",
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Most capable Gemini 2.5 Pro model via Vertex AI Express",
        ja: "Vertex AI Express経由で利用できる最も高性能なGemini 2.5 Proモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3-flash",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Gemini 3 Flash model via Vertex AI Express",
        ja: "Vertex AI Express経由で利用できるGemini 3 Flashモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3-flash-preview",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Preview Gemini 3 Flash model via Vertex AI Express (deprecated, use gemini-3-flash)",
        ja: "Vertex AI Express経由で利用できるGemini 3 Flashプレビューモデル（非推奨、gemini-3-flashを使用）",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3-pro",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Gemini 3 Pro model focused on reasoning via Vertex AI Express",
        ja: "Vertex AI Express経由の推論特化Gemini 3 Proモデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3-pro-preview",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Preview Gemini 3 Pro model focused on reasoning via Vertex AI Express (deprecated, use gemini-3-pro)",
        ja: "Vertex AI Express経由の推論特化Gemini 3 Proプレビューモデル（非推奨、gemini-3-proを使用）",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3.1-pro",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Gemini 3.1 Pro model via Vertex AI Express (deprecated, use gemini-3.1-pro-preview)",
        ja: "Vertex AI Express経由のGemini 3.1 Proモデル（非推奨、gemini-3.1-pro-previewを使用）",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3.1-pro-preview",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Latest Gemini 3.1 Pro preview model via Vertex AI Express",
        ja: "Vertex AI Express経由の最新Gemini 3.1 Proプレビューモデル",
      },
    ],
  },
  {
    comment: "NovelAI Models (text-only, no vision or structured output capabilities)",
    rows: [
      {
        provider: "novelai",
        codename: "glm-4-6",
        isDefault: true,
        isSmartest: true,
        hasTools: true,
        desc: "Latest NovelAI roleplay model with enhanced creativity and character consistency",
        ja: "創造性とキャラクター一貫性を強化した最新のNovelAIロールプレイモデル",
      },
      {
        provider: "novelai",
        codename: "kayra-v1",
        desc: "Legacy Kayra model for storytelling and roleplay",
        ja: "ストーリーテリングとロールプレイ向けのレガシーKayraモデル",
      },
      {
        provider: "novelai",
        codename: "llama-3-erato-v1",
        desc: "Based on the Llama 3 70B Base model, trained on the most high-quality NovelAI storytelling dataset",
        ja: "Llama 3 70Bベースモデルを基に、NovelAI最高品質のストーリーテリングデータセットで学習したモデル",
      },
    ],
  },
  {
    comment: "OpenRouter Models (structured output support varies by model, user configures manually)",
    rows: [
      {
        provider: "openrouter",
        codename: "stepfun-ai/step3",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "General-use model that can see images and is also great in role-play (deprecated, use stepfun/step-3.5-flash)",
        ja: "画像を見ることができ、ロールプレイにも優れた汎用モデル（非推奨、stepfun/step-3.5-flash を使用）",
      },
      {
        provider: "openrouter",
        codename: "stepfun/step-3.5-flash",
        hasTools: true,
        isDeprecated: true,
        desc: "Fast Stepfun model with tool support only",
        ja: "ツール利用のみに対応した高速Stepfunモデル",
      },
      {
        provider: "openrouter",
        codename: "z-ai/glm-4.6",
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "State-of-the-art human-aligned model that also performs natural role-play",
        ja: "自然なロールプレイも可能な最先端の人間調整型モデル",
      },
      {
        provider: "openrouter",
        codename: "z-ai/glm-4.7",
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Latest State-of-the-art human-aligned model that also performs natural role-play",
        ja: "最新の自然なロールプレイも可能な最先端の人間調整型モデル",
      },
      {
        provider: "openrouter",
        codename: "z-ai/glm-4.7-flash",
        hasTools: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Fast GLM 4.7 variant for responsive general-purpose tasks",
        ja: "応答性の高い汎用タスク向けの高速GLM 4.7バリアント",
      },
      {
        provider: "openrouter",
        codename: "z-ai/glm-5",
        hasTools: true,
        supportsStructoutput: true,
        desc: "Latest GLM 5 model with advanced natural language understanding and role-play capabilities",
        ja: "高度な自然言語理解とロールプレイ機能を備えた最新のGLM 5モデル",
      },
      {
        provider: "openrouter",
        codename: "openrouter/pony-alpha",
        isFree: true,
        hasTools: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Free OpenRouter Pony Alpha model with tools and structured output support (DEPRECATED)",
        ja: "ツールと構造化出力に対応した無料のOpenRouter Pony Alphaモデル（非推奨）",
      },
      {
        provider: "openrouter",
        codename: "thedrummer/cydonia-24b-v4.1",
        isUncensored: true,
        supportsStructoutput: true,
        desc: "Uncensored model specializing in creative writing and role-play",
        ja: "創作とロールプレイに特化した無検閲モデル",
      },
      {
        provider: "openrouter",
        codename: "deepseek/deepseek-v3.2-exp",
        hasTools: true,
        isUncensored: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Cost-efficient Experimental Model that is also great in role-play",
        ja: "ロールプレイにも優れたコスト効率の良い実験モデル",
      },
      {
        provider: "openrouter",
        codename: "deepseek/deepseek-v3.2",
        hasTools: true,
        isUncensored: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Cost-efficient stable model that is also great in role-play (deprecated, use deepseek-v4-flash)",
        ja: "ロールプレイにも優れたコスト効率の良い安定版モデル（非推奨、deepseek-v4-flashを使用）",
      },
      {
        provider: "openrouter",
        codename: "deepseek/deepseek-v4-flash",
        hasTools: true,
        isUncensored: true,
        supportsStructoutput: true,
        desc: "Fast and cost-efficient stable model that is also great in role-play",
        ja: "ロールプレイにも優れた高速でコスト効率の良い安定版モデル",
      },
      {
        provider: "openrouter",
        codename: "tngtech/deepseek-r1t2-chimera",
        isReasoning: true,
        hasTools: true,
        isUncensored: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Advanced Chimera DeepSeek model that is great at role-playing",
        ja: "ロールプレイに優れた高度なChimera DeepSeekモデル",
      },
      {
        provider: "openrouter",
        codename: "x-ai/grok-4-fast",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Fast and efficient general-purpose model",
        ja: "高速かつ効率的な汎用モデル",
      },
      {
        provider: "openrouter",
        codename: "x-ai/grok-4.1-fast",
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Latest fast and efficient general-purpose model",
        ja: "高速かつ効率的な汎用モデル",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3-flash-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Gemini 3 Flash preview via OpenRouter with tool use, image understanding, and YouTube video support (deprecated, use google/gemini-3.5-flash)",
        ja: "OpenRouter経由でツール利用・画像理解・YouTube動画処理に対応したGemini 3 Flashプレビュー（非推奨、google/gemini-3.5-flashを使用）",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3.1-flash-lite-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Latest Gemini 3.1 Flash Lite preview via OpenRouter with full multimodal, tool, and YouTube video capabilities",
        ja: "OpenRouter経由でフルマルチモーダル機能・ツール利用・YouTube動画処理に対応した最新のGemini 3.1 Flash Liteプレビューモデル",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3-pro-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Gemini 3 Pro preview via OpenRouter with tool, image, video, and YouTube support (deprecated, use google/gemini-3.1-pro-preview)",
        ja: "OpenRouter経由でツール利用・画像理解・動画・YouTube処理に対応したGemini 3 Proプレビュー（非推奨、google/gemini-3.1-pro-preview を使用）",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3.1-pro-preview",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Latest Gemini 3.1 Pro preview via OpenRouter with tool, image, video, and YouTube support",
        ja: "OpenRouter経由でツール利用・画像理解・動画・YouTube処理に対応した最新のGemini 3.1 Proプレビュー",
      },
      {
        provider: "openrouter",
        codename: "google/gemma-4-31b-it",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "OpenRouter-hosted Google Gemma 4.31B IT model with tool use, vision, and structured output support (video disabled)",
        ja: "動画非対応ながらツール利用・画像理解・構造化出力に対応するOpenRouter経由のGoogle Gemma 4.31B ITモデル",
      },
      {
        provider: "openrouter",
        codename: "google/gemma-4-31b-it:free",
        isDefault: true,
        isFree: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Free OpenRouter-hosted Google Gemma 4.31B IT model with tool use, vision, and structured output support (video disabled)",
        ja: "動画非対応ながらツール利用・画像理解・構造化出力に対応するOpenRouter経由の無料版Google Gemma 4.31B ITモデル",
      },
      {
        provider: "openrouter",
        codename: "anthropic/claude-sonnet-4.5",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "State-of-the-art performance in complex tasks and problems, also great in role-playing and creative writing",
        ja: "複雑なタスクや問題に優れた最先端性能を持ち、ロールプレイや創作にも秀でたモデル",
      },
      {
        provider: "openrouter",
        codename: "anthropic/claude-sonnet-4.6",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Balanced Claude model with strong quality, speed, and cost tradeoffs",
        ja: "品質・速度・コストのバランスに優れたClaudeモデル",
      },
      {
        provider: "openrouter",
        codename: "anthropic/claude-haiku-4.5",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Lightweight version of claude-sonnet-4.5",
        ja: "claude-sonnet-4.5の軽量版",
      },
      {
        provider: "openrouter",
        codename: "openai/gpt-5.1",
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "State-of-the-art performance in complex tasks and problems",
        ja: "複雑なタスクや問題に優れた最先端性能",
      },
      {
        provider: "openrouter",
        codename: "openai/gpt-5.1-chat",
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "State-of-the-art performance, more conversational",
        ja: "複雑なタスクや問題に優れた最先端性能",
      },
      {
        provider: "openrouter",
        codename: "mistralai/mistral-large-2512",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Mistral’s most capable model to date, cheap and multimodal",
        ja: "Mistral史上最も高性能で、低コストなマルチモーダルモデル",
      },
      {
        provider: "openrouter",
        codename: "mistralai/mistral-small-creative",
        hasTools: true,
        isDeprecated: true,
        desc: "Lightweight tool-capable model designed for creative writing and role-playing",
        ja: "創作（文章執筆・ロールプレイ）に特化した軽量ツール対応モデル",
      },
      {
        provider: "openrouter",
        codename: "mistralai/mistral-small-3.1-24b-instruct",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Multimodal lightweight general-purpose model from Mistral",
        ja: "Mistralの軽量マルチモーダル汎用モデル",
      },
      {
        provider: "openrouter",
        codename: "deepseek/deepseek-chat-v3-0324:free",
        isFree: true,
        isUncensored: true,
        isDeprecated: true,
        desc: "Free general-purpose model that also performs good role-play",
        ja: "ロールプレイにも優れた無料の汎用モデル",
      },
      {
        provider: "openrouter",
        codename: "mistralai/mistral-small-3.2-24b-instruct:free",
        isFree: true,
        isDeprecated: true,
        desc: "Free general-purpose model",
        ja: "無料の汎用モデル",
      },
      {
        provider: "openrouter",
        codename: "tngtech/deepseek-r1t2-chimera:free",
        isReasoning: true,
        isFree: true,
        hasTools: true,
        isUncensored: true,
        isDeprecated: true,
        desc: "Free model for solving complex tasks and problems",
        ja: "複雑なタスクや問題の解決に適した無料モデル",
      },
      {
        provider: "openrouter",
        codename: "mistralai/mistral-small-3.1-24b-instruct:free",
        isFree: true,
        hasTools: true,
        seesImages: true,
        isDeprecated: true,
        desc: "Free multimodal model with enhanced reasoning and vision capabilities",
        ja: "強化された推論とビジョン機能を備えた無料のマルチモーダルモデル",
      },
      {
        provider: "openrouter",
        codename: "z-ai/glm-4.5-air:free",
        isFree: true,
        hasTools: true,
        isDeprecated: true,
        desc: "Free lightweight model with thinking mode for reasoning and agent tasks",
        ja: "推論とエージェントタスク向けのシンキングモードを備えた無料軽量モデル",
      },
      {
        provider: "openrouter",
        codename: "tngtech/tng-r1t-chimera:free",
        isFree: true,
        hasTools: true,
        isDeprecated: true,
        desc: "Free experimental model for creative storytelling and character interaction",
        ja: "創作とキャラクター対話に特化した無料の実験モデル",
      },
      {
        provider: "openrouter",
        codename: "qwen/qwen3.5-35b-a3b",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Qwen 3.5 35B A3B model with tool use, vision, and structured output support (deprecated)",
        ja: "ツール利用・画像理解・構造化出力に対応したQwen 3.5 35B A3Bモデル（非推奨）",
      },
      {
        provider: "openrouter",
        codename: "qwen/qwen3.5-27b",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        supportsStructoutput: true,
        desc: "Qwen 3.5 27B model with tool use, vision, and structured output support",
        ja: "ツール利用・画像理解・構造化出力に対応したQwen 3.5 27Bモデル",
      },
      {
        provider: "openrouter",
        codename: "qwen/qwen3.5-flash-02-23",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        supportsStructoutput: true,
        desc: "Fast Qwen 3.5 Flash (02-23) model with tool use, vision, and structured output support",
        ja: "ツール利用・画像理解・構造化出力に対応した高速Qwen 3.5 Flash（02-23）モデル",
      },
      {
        provider: "openrouter",
        codename: "nvidia/nemotron-3-super-120b-a12b",
        hasTools: true,
        supportsStructoutput: true,
        desc: "Nemotron model with tool use and structured output support",
        ja: "ツール利用と構造化出力に対応したNemotronモデル",
      },
      {
        provider: "openrouter",
        codename: "nvidia/nemotron-3-super-120b-a12b:free",
        isFree: true,
        hasTools: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Free Nemotron model with tool use and structured output support (deprecated, use non-free variant)",
        ja: "ツール利用と構造化出力に対応した無料のNemotronモデル（非推奨、有料バージョンを使用）",
      },
      {
        provider: "openrouter",
        codename: "moonshotai/kimi-k2.5",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        isDeprecated: true,
        desc: "Moonshot AI's state-of-the-art native multimodal model",
        ja: "Moonshot AIの最先端ネイティブ・マルチモーダルモデル",
      },
      {
        provider: "openrouter",
        codename: "moonshotai/kimi-k2.6",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Latest Moonshot AI native multimodal model",
        ja: "Moonshot AIの最新ネイティブ・マルチモーダルモデル",
      },
      {
        provider: "openrouter",
        codename: "aion-labs/aion-2.0",
        isDeprecated: true,
        desc: "Cheap role-play fine-tune of DeepSeek with no tools, vision, or structured output support",
        ja: "ツール・画像理解・構造化出力に対応しない、DeepSeekベースの低コストなロールプレイ特化ファインチューニングモデル",
      },
      {
        provider: "openrouter",
        codename: "account-setting",
        isDeprecated: true,
        desc: "Legacy codename (deprecated, use other-model)",
        ja: "旧コードネーム（非推奨、other-modelを使用）",
      },
      {
        provider: "openrouter",
        codename: "other-model",
        hasTools: true,
        seesImages: true,
        seesVideos: true,
        seesYoutube: true,
        supportsStructoutput: true,
        desc: "Advanced: Use any OpenRouter model by entering its codename",
        ja: "上級者向け：コードネームを入力して任意のOpenRouterモデルを使用",
      },
      {
        provider: "openrouter",
        codename: "rekaai/reka-edge",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Extremely efficient and cheap multimodal model, recommended to pair with a blind model for image captioning",
        ja: "非常に効率的で安価なマルチモーダルモデル、画像キャプション用にテキスト専用モデルとペアリングすることを推奨",
      },
    ],
  },
  {
    comment: "DeepSeek Models (bounded MVP: text chat + seeded tool calling only)",
    rows: [
      {
        provider: "deepseek",
        codename: "deepseek-v4-flash",
        supportsPrefixCompletion: true,
        isDefault: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Fast and cost-efficient default DeepSeek v4 model with tool support and structured output",
        ja: "ツール利用と構造化出力に対応した、高速でコスト効率の良いデフォルトのDeepSeek v4モデル",
      },
      {
        provider: "deepseek",
        codename: "deepseek-v4-pro",
        supportsPrefixCompletion: true,
        isSmartest: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Highly capable DeepSeek v4 model with tool support and structured output",
        ja: "ツール利用と構造化出力に対応した、高性能なDeepSeek v4モデル",
      },
      {
        provider: "deepseek",
        codename: "deepseek-chat",
        supportsPrefixCompletion: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "DeepSeek chat model for general text generation, seeded tool use, and JSON structured output",
        ja: "汎用テキスト生成、シード済みツール利用、JSON構造化出力に対応したDeepSeekチャットモデル",
      },
      {
        provider: "deepseek",
        codename: "deepseek-reasoner",
        supportsPrefixCompletion: true,
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Reasoning-focused DeepSeek model with thinking mode, seeded tool use, and JSON structured output",
        ja: "シンキングモード、シード済みツール利用、JSON構造化出力に対応した、推論特化のDeepSeekモデル",
      },
    ],
  },
  {
    comment: "NVIDIA NIM Models (curated hosted NVIDIA catalog)",
    rows: [
      {
        provider: "nvidia",
        codename: "deepseek-ai/deepseek-v3.2",
        isDefault: true,
        isFree: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Default NVIDIA NIM chat model with tool support and structured output",
        ja: "ツール利用と構造化出力に対応した、NVIDIA NIMのデフォルトチャットモデル",
      },
      {
        provider: "nvidia",
        codename: "qwen/qwen3.5-397b-a17b",
        isSmartest: true,
        isFree: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Most capable multimodal NVIDIA NIM model in TomoriBot's curated set",
        ja: "TomoriBotの厳選NVIDIA NIMセット内で最も高性能なマルチモーダルモデル",
      },
      {
        provider: "nvidia",
        codename: "moonshotai/kimi-k2-instruct",
        desc: "General-purpose NVIDIA NIM text model without tool or structured-output support",
        ja: "ツール利用や構造化出力に対応しない、NVIDIA NIMの汎用テキストモデル",
      },
      {
        provider: "nvidia",
        codename: "z.ai/glm-4.7",
        isFree: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Tool-capable NVIDIA NIM GLM model with structured output support",
        ja: "ツール利用と構造化出力に対応した、NVIDIA NIMのGLMモデル",
      },
      {
        provider: "nvidia",
        codename: "stepfun-ai/step-3.5-flash",
        isFree: true,
        hasTools: true,
        desc: "Fast NVIDIA NIM chat model with tool support only",
        ja: "ツール利用のみに対応した高速NVIDIA NIMチャットモデル",
      },
      {
        provider: "nvidia",
        codename: "google/gemma-3-27b-it",
        isFree: true,
        seesImages: true,
        isDeprecated: true,
        desc: "Vision-capable NVIDIA NIM Gemma model for image understanding",
        ja: "画像理解に対応した、NVIDIA NIMのGemmaビジョンモデル",
      },
      {
        provider: "nvidia",
        codename: "google/gemma-4-31b-it",
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Vision-capable NVIDIA NIM Gemma 4.31B IT model with tool use and structured output (video disabled)",
        ja: "動画非対応ながらツール利用と構造化出力に対応するNVIDIA NIM向けGemma 4.31B ITモデル",
      },
      {
        provider: "nvidia",
        codename: "deepseek-ai/deepseek-v4-flash",
        hasTools: true,
        isUncensored: true,
        supportsStructoutput: true,
        desc: "Fast and cost-efficient DeepSeek v4 model via NVIDIA NIM with tool support and structured output",
        ja: "NVIDIA NIM経由でツール利用と構造化出力に対応した、高速でコスト効率の良いDeepSeek v4モデル",
      },
    ],
  },
  {
    comment: "Z.ai (Coding) Models (plain codenames preserved for backward compatibility)",
    rows: [
      {
        provider: "zaicoding",
        codename: "glm-4.6",
        supportsPrefixCompletion: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Text-only GLM model optimized for roleplay",
        ja: "ロールプレイ向けに最適化されたテキスト専用GLMモデル",
      },
      {
        provider: "zaicoding",
        codename: "glm-4.6v",
        supportsPrefixCompletion: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Vision-capable GLM model with image understanding, tool use, and structured output",
        ja: "画像理解、ツール利用、構造化出力に対応したビジョン対応GLMモデル",
      },
      {
        provider: "zaicoding",
        codename: "glm-4.6v-flash",
        supportsPrefixCompletion: true,
        isFree: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Fast and free vision-capable GLM model routed through the Z.ai Coding endpoint",
        ja: "Z.ai Codingエンドポイント経由で利用する高速かつ無料のビジョン対応GLMモデル",
      },
      {
        provider: "zaicoding",
        codename: "glm-4.7",
        supportsPrefixCompletion: true,
        isDefault: true,
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Reasoning-capable GLM model with thinking mode, tool use, and structured output",
        ja: "シンキングモード、ツール利用、構造化出力に対応した推論対応GLMモデル",
      },
      {
        provider: "zaicoding",
        codename: "glm-4.7-flash",
        supportsPrefixCompletion: true,
        isFree: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Fast GLM model routed through the Z.ai Coding endpoint",
        ja: "Z.ai Codingエンドポイント経由で利用する高速GLMモデル",
      },
      {
        provider: "zaicoding",
        codename: "glm-5",
        supportsPrefixCompletion: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Most capable GLM model with advanced reasoning, tool use, and structured output",
        ja: "高度な推論、ツール利用、構造化出力に対応した最も高性能なGLMモデル",
      },
      {
        provider: "zaicoding",
        codename: "glm-5.1",
        supportsPrefixCompletion: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Latest flagship GLM model with advanced reasoning and tool support",
        ja: "最新のフラッグシップGLMモデル（高度な推論・ツール対応）",
      },
      {
        provider: "zaicoding",
        codename: "glm-5-turbo",
        supportsPrefixCompletion: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Fast variant of GLM-5 with tool support",
        ja: "GLM-5の高速版（ツール対応）",
      },
      {
        provider: "zaicoding",
        codename: "glm-5v-turbo",
        supportsPrefixCompletion: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Vision-capable GLM-5 Turbo tuned for long contexts and reliable tool chains",
        ja: "長文コンテキスト対応と安定したツール連携に調整されたビジョン対応GLM-5 Turboモデル",
      },
    ],
  },
  {
    comment: "Z.ai General API Models (prefixed codenames allow coexistence with coding rows)",
    rows: [
      {
        provider: "zai",
        codename: "zai/glm-4.6",
        supportsPrefixCompletion: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Text-only GLM model optimized for roleplay",
        ja: "ロールプレイ向けに最適化されたテキスト専用GLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-4.6v",
        supportsPrefixCompletion: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Vision-capable GLM model from the general Z.ai API",
        ja: "通常のZ.ai APIで利用するビジョン対応GLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-4.6v-flash",
        supportsPrefixCompletion: true,
        isFree: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Fast and free vision-capable GLM model from the general Z.ai API",
        ja: "通常のZ.ai APIで利用する高速かつ無料のビジョン対応GLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-4.7",
        supportsPrefixCompletion: true,
        isDefault: true,
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Reasoning-capable GLM model from the general Z.ai API",
        ja: "通常のZ.ai APIで利用する推論対応GLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-4.7-flash",
        supportsPrefixCompletion: true,
        isFree: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Fast and free GLM model from the general Z.ai API",
        ja: "通常のZ.ai APIで利用する高速で無料のGLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-5",
        supportsPrefixCompletion: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Most capable GLM model from the general Z.ai API",
        ja: "通常のZ.ai APIで利用する最も高性能なGLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-5.1",
        supportsPrefixCompletion: true,
        isReasoning: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Latest flagship GLM model from the general Z.ai API",
        ja: "通常のZ.ai APIで利用する最新のフラッグシップGLMモデル",
      },
      {
        provider: "zai",
        codename: "zai/glm-5-turbo",
        supportsPrefixCompletion: true,
        hasTools: true,
        supportsStructoutput: true,
        desc: "Fast variant of GLM-5 from the general Z.ai API",
        ja: "通常のZ.ai APIで利用するGLM-5の高速版",
      },
      {
        provider: "zai",
        codename: "zai/glm-5v-turbo",
        supportsPrefixCompletion: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Vision-capable GLM-5 Turbo tuned for long contexts and reliable tool chains",
        ja: "長文コンテキスト対応と安定したツール連携に調整されたビジョン対応GLM-5 Turboモデル",
      },
    ],
  },
  {
    comment: "Anthropic Models (vision + tools + structured output via forced tool use; no video/YouTube)",
    rows: [
      {
        provider: "anthropic",
        codename: "claude-haiku-4-5",
        strictRoleAlternation: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Fast and cost-efficient Claude model for general tasks",
        ja: "汎用タスク向けの高速でコスト効率の良いClaudeモデル",
      },
      {
        provider: "anthropic",
        codename: "claude-sonnet-4-6",
        strictRoleAlternation: true,
        isDefault: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Balanced Claude model — best mix of quality, speed, and cost",
        ja: "品質・速度・コストの最適なバランスを持つClaudeモデル",
      },
      {
        provider: "anthropic",
        codename: "claude-opus-4-6",
        strictRoleAlternation: true,
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Most capable Claude model with extended thinking for complex reasoning",
        ja: "複雑な推論向けの拡張思考機能を持つ最高性能のClaudeモデル",
      },
      {
        provider: "anthropic",
        codename: "claude-opus-4-7",
        strictRoleAlternation: true,
        isSmartest: true,
        isReasoning: true,
        hasTools: true,
        seesImages: true,
        supportsStructoutput: true,
        desc: "Most capable Claude model with extended thinking for complex reasoning",
        ja: "複雑な推論向けの拡張思考機能を持つ最高性能のClaudeモデル",
      },
    ],
  },
  {
    comment: [
      'Custom Provider Bootstrap Entry (allows "custom" to appear in provider dropdown)',
      "Actual capabilities are configured per-server when users set up their custom endpoint",
    ],
    rows: [
      {
        provider: "custom",
        codename: "custom/bootstrap",
        isFree: true,
        isUncensored: true,
        desc: "Self-hosted OpenAI-compatible endpoint (Ollama, KoboldCPP, vLLM, LocalAI)",
        ja: "セルフホスト型OpenAI互換エンドポイント（Ollama、KoboldCPP、vLLM、LocalAI）",
      },
    ],
  },
];

export const imageSections: ModelSection<ImageInput>[] = [
  {
    comment: "Google Gemini Image Generation Models",
    rows: [
      {
        provider: "google",
        codename: "gemini-2.5-flash-image",
        isDefault: true,
        desc: "Fast and efficient image generation model with balanced quality and speed",
        ja: "品質と速度のバランスが取れた高速で効率的な画像生成モデル",
      },
      {
        provider: "google",
        codename: "gemini-3.1-flash-image",
        desc: "Latest fast image generation model with Gemini 3.1 Flash",
        ja: "Gemini 3.1 Flashによる最新の高速画像生成モデル",
      },
      {
        provider: "google",
        codename: "gemini-3.1-flash-image-preview",
        isDeprecated: true,
        desc: "Latest fast image generation preview model with Gemini 3.1 Flash (deprecated, use gemini-3.1-flash-image)",
        ja: "Gemini 3.1 Flashによる最新の高速画像生成プレビューモデル（非推奨、gemini-3.1-flash-imageを使用）",
      },
      {
        provider: "google",
        codename: "gemini-3-pro-image",
        desc: "Advanced image generation model with higher resolution support (1K/2K/4K) and enhanced quality",
        ja: "高解像度対応（1K/2K/4K）と強化された品質を備えた高度な画像生成モデル",
      },
      {
        provider: "google",
        codename: "gemini-3-pro-image-preview",
        isDeprecated: true,
        desc: "Advanced image generation model with higher resolution support (1K/2K/4K) and enhanced quality (deprecated, use gemini-3-pro-image)",
        ja: "高解像度対応（1K/2K/4K）と強化された品質を備えた高度な画像生成モデル（非推奨、gemini-3-pro-imageを使用）",
      },
    ],
  },
  {
    comment: "OpenRouter Gemini Image Generation Models (via OpenRouter API)",
    rows: [
      {
        provider: "openrouter",
        codename: "google/gemini-2.5-flash-image",
        isDefault: true,
        desc: "Fast and efficient image generation via OpenRouter with balanced quality and speed",
        ja: "OpenRouter経由の品質と速度のバランスが取れた高速で効率的な画像生成",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3.1-flash-image",
        desc: "Latest fast image generation via OpenRouter with Gemini 3.1 Flash Image",
        ja: "Gemini 3.1 Flash ImageによるOpenRouter経由の最新高速画像生成",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3.1-flash-image-preview",
        isDeprecated: true,
        desc: "Latest fast image generation via OpenRouter with Gemini 3.1 Flash Image Preview (deprecated, use google/gemini-3.1-flash-image)",
        ja: "Gemini 3.1 Flash Image PreviewによるOpenRouter経由の最新高速画像生成（非推奨、google/gemini-3.1-flash-imageを使用）",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3-pro-image",
        desc: "Advanced image generation via OpenRouter with enhanced quality and resolution options",
        ja: "OpenRouter経由の強化された品質と解像度オプションを備えた高度な画像生成",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-3-pro-image-preview",
        isDeprecated: true,
        desc: "Advanced image generation via OpenRouter with enhanced quality and resolution options (deprecated, use google/gemini-3-pro-image)",
        ja: "OpenRouter経由の強化された品質と解像度オプションを備えた高度な画像生成（非推奨、google/gemini-3-pro-imageを使用）",
      },
    ],
  },
  {
    comment: "Vertex AI Gemini Image Generation Models",
    rows: [
      {
        provider: "vertex",
        codename: "gemini-2.5-flash-image",
        isDefault: true,
        desc: "Fast and efficient Gemini image generation via Vertex AI with balanced quality and speed",
        ja: "Vertex AI経由で利用する、品質と速度のバランスが取れた高速Gemini画像生成モデル",
      },
      {
        provider: "vertex",
        codename: "gemini-3.1-flash-image",
        desc: "Latest fast image generation via Vertex AI with Gemini 3.1 Flash Image",
        ja: "Gemini 3.1 Flash ImageによるVertex AI経由の最新高速画像生成",
      },
      {
        provider: "vertex",
        codename: "gemini-3.1-flash-image-preview",
        isDeprecated: true,
        desc: "Latest fast image generation via Vertex AI with Gemini 3.1 Flash Image Preview (deprecated, use gemini-3.1-flash-image)",
        ja: "Gemini 3.1 Flash Image PreviewによるVertex AI経由の最新高速画像生成（非推奨、gemini-3.1-flash-imageを使用）",
      },
      {
        provider: "vertex",
        codename: "gemini-3-pro-image",
        desc: "Advanced image generation via Vertex AI with enhanced quality and resolution options",
        ja: "Vertex AI経由の強化された品質と解像度オプションを備えた高度な画像生成",
      },
      {
        provider: "vertex",
        codename: "gemini-3-pro-image-preview",
        isDeprecated: true,
        desc: "Advanced image generation via Vertex AI with enhanced quality and resolution options (deprecated, use gemini-3-pro-image)",
        ja: "Vertex AI経由の強化された品質と解像度オプションを備えた高度な画像生成（非推奨、gemini-3-pro-imageを使用）",
      },
    ],
  },
  {
    comment: "Vertex AI Express Gemini Image Generation Models",
    rows: [
      {
        provider: "vertexexpress",
        codename: "gemini-2.5-flash-image",
        isDefault: true,
        desc: "Fast and efficient Gemini image generation via Vertex AI Express with balanced quality and speed",
        ja: "Vertex AI Express経由で利用する、品質と速度のバランスが取れた高速Gemini画像生成モデル",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3.1-flash-image",
        desc: "Latest fast image generation via Vertex AI Express with Gemini 3.1 Flash Image",
        ja: "Gemini 3.1 Flash ImageによるVertex AI Express経由の最新高速画像生成",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3.1-flash-image-preview",
        isDeprecated: true,
        desc: "Latest fast image generation via Vertex AI Express with Gemini 3.1 Flash Image Preview (deprecated, use gemini-3.1-flash-image)",
        ja: "Gemini 3.1 Flash Image PreviewによるVertex AI Express経由の最新高速画像生成（非推奨、gemini-3.1-flash-imageを使用）",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3-pro-image",
        desc: "Advanced image generation via Vertex AI Express with enhanced quality and resolution options",
        ja: "Vertex AI Express経由の強化された品質と解像度オプションを備えた高度な画像生成",
      },
      {
        provider: "vertexexpress",
        codename: "gemini-3-pro-image-preview",
        isDeprecated: true,
        desc: "Advanced image generation via Vertex AI Express with enhanced quality and resolution options (deprecated, use gemini-3-pro-image)",
        ja: "Vertex AI Express経由の強化された品質と解像度オプションを備えた高度な画像生成（非推奨、gemini-3-pro-imageを使用）",
      },
      {
        provider: "openrouter",
        codename: "openai/gpt-5-image-mini",
        desc: "Lightweight OpenAI image generation model via OpenRouter",
        ja: "OpenRouter経由の軽量なOpenAI画像生成モデル",
      },
      {
        provider: "openrouter",
        codename: "bytedance-seed/seedream-4.5",
        desc: "Latest in-house image generation model developed by ByteDance. Cheap and high performance",
        ja: "ByteDanceが開発した最新の自社製画像生成モデル。低コストかつ高性能",
      },
    ],
  },
  {
    comment: "Z.ai General API Image Generation Models",
    rows: [
      {
        provider: "zai",
        codename: "zai/glm-image",
        isDefault: true,
        desc: "Z.ai native image generation model with HD quality output",
        ja: "HD品質の出力に対応したZ.aiネイティブ画像生成モデル",
      },
    ],
  },
  {
    comment: "NVIDIA NIM Image Generation Models",
    rows: [
      {
        provider: "nvidia",
        codename: "stabilityai/stable-diffusion-3-medium",
        isDefault: true,
        desc: "NVIDIA-hosted Stable Diffusion 3 Medium image generation model",
        ja: "NVIDIAホストのStable Diffusion 3 Medium画像生成モデル",
      },
    ],
  },
  {
    comment: "NovelAI Diffusion Models",
    rows: [
      {
        provider: "novelai",
        codename: "nai-diffusion-3-furry",
        isUncensored: true,
        desc: "NovelAI furry-specialized diffusion model",
        ja: "NovelAIのファーリー特化型拡散モデル",
      },
      {
        provider: "novelai",
        codename: "nai-diffusion-4-5-full",
        isDefault: true,
        isUncensored: true,
        desc: "NovelAI Diffusion 4.5 full model with uncensored generation",
        ja: "NovelAI Diffusion 4.5 フルモデル（無検閲生成対応）",
      },
      {
        provider: "novelai",
        codename: "nai-diffusion-4-5-curated",
        isUncensored: true,
        desc: "NovelAI Diffusion 4.5 curated model with refined outputs",
        ja: "NovelAI Diffusion 4.5 キュレーションモデル（洗練された出力）",
      },
    ],
  },
];

export const videoSections: ModelSection<VideoInput>[] = [
  {
    comment: "Google Veo Video Generation Models",
    rows: [
      {
        provider: "google",
        codename: "veo-3.1-generate-preview",
        isDefault: true,
        desc: "Google Veo 3.1 — 8-second 720p/1080p/4K videos with native audio generation",
        ja: "Google Veo 3.1 — ネイティブオーディオ生成付き8秒の720p/1080p/4K動画",
      },
      {
        provider: "google",
        codename: "veo-3.1-fast-generate-preview",
        desc: "Google Veo 3.1 Fast — faster video generation with reduced quality",
        ja: "Google Veo 3.1 Fast — 品質を抑えた高速動画生成",
      },
      {
        provider: "google",
        codename: "veo-3.1-lite-generate-preview",
        desc: "Google Veo 3.1 Lite — lightweight video generation (no 4K support)",
        ja: "Google Veo 3.1 Lite — 軽量な動画生成（4K非対応）",
      },
    ],
  },
  {
    comment: "OpenRouter Video Generation Models",
    rows: [
      {
        provider: "openrouter",
        codename: "bytedance/seedance-1-5-pro",
        isDefault: true,
        desc: "ByteDance Seedance 1.5 Pro — high-quality video generation with 4-12s duration",
        ja: "ByteDance Seedance 1.5 Pro — 4〜12秒の高品質動画生成",
      },
      {
        provider: "openrouter",
        codename: "google/veo-3.1",
        desc: "Google Veo 3.1 via OpenRouter — 8-second videos with native audio",
        ja: "OpenRouter経由のGoogle Veo 3.1 — ネイティブオーディオ付き8秒動画",
      },
      {
        provider: "openrouter",
        codename: "alibaba/wan-2.6",
        desc: "Alibaba Wan 2.6 — versatile video generation with multiple resolutions",
        ja: "Alibaba Wan 2.6 — 複数解像度対応の多機能動画生成",
      },
      {
        provider: "openrouter",
        codename: "openai/sora-2-pro",
        desc: "OpenAI Sora 2 Pro — high-fidelity video generation up to 20 seconds",
        ja: "OpenAI Sora 2 Pro — 最大20秒の高忠実度動画生成",
      },
    ],
  },
  {
    comment: "Z.ai Video Generation Models",
    rows: [
      {
        provider: "zai",
        codename: "cogvideox-3",
        isDefault: true,
        desc: "CogVideoX-3 — Z.ai video generation with up to 4K resolution and audio support",
        ja: "CogVideoX-3 — 最大4K解像度とオーディオ対応のZ.ai動画生成",
      },
    ],
  },
];

export const embeddingSections: ModelSection<EmbeddingInput>[] = [
  {
    comment: "Google Gemini Embedding Models",
    rows: [
      {
        provider: "google",
        codename: "gemini-embedding-001",
        family: "gemini-embedding-001",
        desc: "Gemini embedding model for document retrieval",
        ja: "文書検索向けのGemini埋め込みモデル",
      },
      {
        provider: "google",
        codename: "gemini-embedding-2",
        family: "gemini-embedding-2",
        isDefault: true,
        desc: "Default Gemini embedding model for document retrieval",
        ja: "文書検索向けのGeminiデフォルト埋め込みモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-embedding-001",
        family: "gemini-embedding-001",
        desc: "Gemini embedding model for document retrieval via Vertex AI",
        ja: "Vertex AI経由の文書検索向けGemini埋め込みモデル",
      },
      {
        provider: "vertex",
        codename: "gemini-embedding-2",
        family: "gemini-embedding-2",
        isDefault: true,
        desc: "Default Gemini embedding model for document retrieval via Vertex AI",
        ja: "Vertex AI経由の文書検索向けGeminiデフォルト埋め込みモデル",
      },
    ],
  },
  {
    comment: "OpenRouter Embedding Models (via OpenRouter API)",
    rows: [
      {
        provider: "openrouter",
        codename: "google/gemini-embedding-001",
        family: "gemini-embedding-001",
        desc: "Gemini embedding model via OpenRouter (same family as Google)",
        ja: "OpenRouter経由のGemini埋め込みモデル（Googleと同一ファミリー）",
      },
      {
        provider: "openrouter",
        codename: "google/gemini-embedding-2",
        family: "gemini-embedding-2",
        desc: "Gemini embedding model via OpenRouter (same family as Google)",
        ja: "OpenRouter経由のGemini埋め込みモデル（Googleと同一ファミリー）",
      },
      {
        provider: "openrouter",
        codename: "intfloat/multilingual-e5-large",
        family: "multilingual-e5-large",
        isDefault: true,
        desc: "Default multilingual embedding model via OpenRouter",
        ja: "OpenRouter経由のデフォルト多言語埋め込みモデル",
      },
      {
        provider: "openrouter",
        codename: "perplexity/pplx-embed-v1-4b",
        family: "pplx-embed-v1-4b",
        desc: "Perplexity embedding model via OpenRouter",
        ja: "OpenRouter経由のPerplexity埋め込みモデル",
      },
      {
        provider: "openrouter",
        codename: "qwen/qwen3-embedding-8b",
        family: "qwen3-embedding-8b",
        isDeprecated: true,
        desc: "Deprecated embedding model (not selectable)",
        ja: "非推奨の埋め込みモデル（選択不可）",
      },
      {
        provider: "openrouter",
        codename: "openai/text-embedding-3-small",
        family: "text-embedding-3-small",
        isDeprecated: true,
        desc: "Deprecated embedding model (not selectable)",
        ja: "非推奨の埋め込みモデル（選択不可）",
      },
      {
        provider: "nvidia",
        codename: "nv-embed-v1",
        family: "nv-embed-v1",
        isDefault: true,
        desc: "Default NVIDIA NIM embedding model for retrieval and document indexing",
        ja: "検索と文書インデックス向けのNVIDIA NIMデフォルト埋め込みモデル",
      },
    ],
  },
];
