import { describe, expect, test } from "bun:test";
import { Collection, ComponentType, type Message } from "discord.js";
import { collectImageUrlsFromMessage } from "@/utils/image/imageExtractor";

/**
 * Build a minimal Message-like object for discovery tests. Only the fields read
 * by `collectImageUrlsFromMessage` (and the shared component scanner) are populated;
 * the rest is cast away because the helper never touches them.
 */
function makeMessage(overrides: {
  attachments?: Array<{ id: string; name: string; url: string; proxyURL: string; contentType: string | null }>;
  embeds?: Message["embeds"];
  stickers?: Array<{ id: string; name: string; url: string }>;
  content?: string;
  components?: unknown[];
}): Message {
  const attachments = new Collection<string, unknown>();
  for (const attachment of overrides.attachments ?? []) {
    attachments.set(attachment.id, attachment);
  }

  const stickers = new Collection<string, unknown>();
  for (const sticker of overrides.stickers ?? []) {
    stickers.set(sticker.id, sticker);
  }

  return {
    attachments,
    stickers,
    embeds: overrides.embeds ?? [],
    content: overrides.content ?? "",
    components: overrides.components ?? [],
  } as unknown as Message;
}

/** Mirror the Components V2 payload generated by the image tools (Media Gallery + footer). */
function mediaGalleryComponent(url: string, contentType: string | null = "image/png"): unknown {
  return {
    type: ComponentType.MediaGallery,
    items: [{ media: { url, proxy_url: `${url}?proxy`, content_type: contentType } }],
  };
}

describe("collectImageUrlsFromMessage", () => {
  test("discovers an image referenced only inside a Components V2 media gallery", () => {
    // Regression: bot-generated images live in a Media Gallery component, not in
    // top-level attachments/embeds. Discovery must still find them.
    const message = makeMessage({
      attachments: [],
      components: [
        mediaGalleryComponent("https://cdn.discordapp.com/attachments/1/2/generated_123.png"),
        { type: ComponentType.TextDisplay, content: "-# Generated after 4.2 seconds." },
      ],
    });

    const urls = collectImageUrlsFromMessage(message);

    expect(urls).toHaveLength(1);
    expect(urls[0]?.url).toBe("https://cdn.discordapp.com/attachments/1/2/generated_123.png");
    expect(urls[0]?.mimeType).toBe("image/png");
    expect(urls[0]?.source).toContain("component:");
  });

  test("returns empty for a message with no media in any source", () => {
    const message = makeMessage({ content: "just text" });
    expect(collectImageUrlsFromMessage(message)).toHaveLength(0);
  });

  test("finds direct image attachments", () => {
    const message = makeMessage({
      attachments: [
        {
          id: "10",
          name: "photo.png",
          url: "https://cdn.discordapp.com/attachments/1/2/photo.png",
          proxyURL: "https://media.discordapp.net/attachments/1/2/photo.png",
          contentType: "image/png",
        },
      ],
    });

    const urls = collectImageUrlsFromMessage(message);
    expect(urls).toHaveLength(1);
    expect(urls[0]?.source).toContain("attachment:");
  });

  test("does not double-count media present as both an attachment and a component reference", () => {
    // A Components V2 message uploads the file (attachment) AND references it in a
    // gallery. The component scanner resolves the candidate back to the same
    // attachment URL, so dedup must keep it to a single entry.
    const sharedUrl = "https://cdn.discordapp.com/attachments/1/2/generated_123.png";
    const message = makeMessage({
      attachments: [
        {
          id: "20",
          name: "generated_123.png",
          url: sharedUrl,
          proxyURL: `${sharedUrl}?proxy`,
          contentType: "image/png",
        },
      ],
      components: [mediaGalleryComponent("attachment://generated_123.png")],
    });

    const urls = collectImageUrlsFromMessage(message);
    expect(urls).toHaveLength(1);
  });
});
